### ISSUE TITLE
[Roadmap] LiteWebAgent Roadmap Q4 2024

### ISSUE THREAD

**Issue by TataKKKL** [PathOnAI/LiteWebAgent#110]
## 1. MCTS @Tata0703 
Please contact @Tata0703 to be added to the separate repo.
- [x] https://github.com/PathOnAI/search-webagent-backend/issues/5
    - [x] https://github.com/PathOnAI/search-webagent-backend/issues/2
    - [ ] https://github.com/PathOnAI/LiteWebAgent/issues/38
    - [ ] https://github.com/PathOnAI/LiteWebAgent/issues/27
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/108 

## 2. Paper Writing @Tata0703 
- [x] https://github.com/Tata0703/LiteWebAgent-paper

## 3. Memory
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/109

## 4. computer control agent @Tata0703 @BRama10 
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/106
- [x] https://github.com/PathOnAI/LiteGUIAgent
- [ ] https://github.com/PathOnAI/LiteMultiAgent/issues/75
- [ ] https://github.com/PathOnAI/LiteWebAgent/issues/105

## 5. UI improvement
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/84
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/112
## 7. Integration
- [ ] https://github.com/PathOnAI/LiteWebAgent/issues/107

## 8. evaluation
- [ ] web agent evaluation
