### ISSUE TITLE
[Roadmap] LiteWebAgent Roadmap Q3 2024

### ISSUE THREAD

**Issue by TataKKKL** [PathOnAI/LiteWebAgent#111]
V1 release

## v0 implementation
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/2
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/1

## Baseline: function calling for action generation, browsergym for action grounding
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/13
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/5
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/3
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/19
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/60
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/52
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/42
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/37
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/33

## Input feature
- [ ] https://github.com/PathOnAI/LiteWebAgent/issues/14
- [ ] https://github.com/PathOnAI/LiteWebAgent/issues/18
- [ ] https://github.com/PathOnAI/LiteWebAgent/issues/29
- [ ] https://github.com/PathOnAI/LiteWebAgent/issues/24

## Evaluation
- [ ] https://github.com/PathOnAI/LiteWebAgent/issues/9

## Planning
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/22
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/23
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/21
- [ ] make plan: https://github.com/PathOnAI/LiteWebAgent/issues/16
- [ ] https://github.com/PathOnAI/LiteWebAgent/issues/34
- [ ] https://github.com/PathOnAI/LiteWebAgent/issues/25

## Prompting Agent
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/58
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/53

## Search agent & Replay
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/77
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/76
   - [x] https://github.com/PathOnAI/LiteWebAgent/pull/69
   - [x] https://github.com/PathOnAI/LiteWebAgent/issues/56
   - [x] https://github.com/PathOnAI/LiteWebAgent/issues/30
   - [x] https://github.com/PathOnAI/LiteWebAgent/issues/26

## Interface
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/67
- [x] https://github.com/PathOnAI/LiteWebAgent/issues/28
- [ ] https://github.com/PathOnAI/LiteWebAgent/issues/12
